In [11]:
import numpy as np


def array_factory(
    mode: str,
    shape: tuple | int,
    value: int | float | None = None
) -> np.ndarray:
    """
    Creates various NumPy arrays based on the mode.

    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.

    """

    """
    Create a NumPy array based on the specified mode.

    Args:
        mode (str): The type of array to create. Supported modes are
            'zeros', 'ones', 'full', and 'identity'.
        shape (tuple or int): The shape of the array. For 'identity',
            this should be an integer representing the matrix size.
        value (int or float, optional): The value used to fill the array
            when mode is 'full'. Defaults to None.

    Returns:
        numpy.ndarray: A NumPy array created according to the selected mode.
    """

    mode = mode.lower()

    if mode == "zeros":
        return np.zeros(shape)

    elif mode == "ones":
        return np.ones(shape)

    elif mode == "full":
        return np.full(shape, value)

    elif mode == "identity":
        return np.identity(shape)

In [13]:
# Test zeros
print("Zeros:")
print(array_factory("ZEROS", (3, 3)))


# Test ones
print("\nOnes:")
print(array_factory("OnEs", (3, 3)))

# Test full
print("\nFull:")
print(array_factory("full", (3, 3), 7))


# Test identity
print("\nIdentity:")
print(array_factory("identity", 4))

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [1]:
import numpy as np


def secure_reshape_and_stack(
    data1: list,
    data2: list,
    new_shape: tuple
) -> np.ndarray:
    """
    Convert two datasets to NumPy arrays, reshape the first dataset,
    and vertically stack both arrays into a single array.

    The first dataset is reshaped according to the specified new_shape.
    Then, the reshaped first array and the second array are combined
    vertically using NumPy's vstack function.

    Args:
        data1 (list): The first dataset to convert and reshape.
        data2 (list): The second dataset to convert to a NumPy array.
        new_shape (tuple): The new shape for the first dataset.

    Returns:
        np.ndarray: A combined NumPy array containing both datasets.

    Raises:
        ValueError: If the new shape is incompatible with data1 or
            the arrays cannot be vertically stacked.
    """

    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)

        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Composite Error: {e}")

In [2]:
data1 = [1, 2, 3, 4, 5, 6]

data2 = [
    [7, 8, 9],
    [10, 11, 12]
]

new_shape = (2, 3)

result = secure_reshape_and_stack(data1, data2, new_shape)

print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
